trigger:

- master

 

pool:

  vmImage: 'windows-latest'

 

variables:

  solution: '**/*.sln'

  buildPlatform: 'Any CPU'

  buildConfiguration: 'Release'

 

steps:

- task: NuGetToolInstaller@1

 

- task: NuGetCommand@2

  inputs:

    restoreSolution: '$(solution)'

 

- task: VSBuild@1

  inputs:

    solution: '$(solution)'

    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'

    platform: '$(buildPlatform)'

    configuration: '$(buildConfiguration)'




- task: DotNetCoreCLI@2

  inputs:

    command: 'publish'

    publishWebProjects: false

    projects: '**/*.sln'

 

- task: AzureRmWebAppDeployment@4

  inputs:

    ConnectionType: 'PublishProfile'

    PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/*- Zip Deploy.pubxml'

    PublishProfilePassword: 'aZN40tk5qxvzjuclhvcnlnziNEfESk0aZpLpEsvxWhQahu0pWle3rrFi3LWF'

    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'