# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to:  $(build.artifactstagingdirectory)/Templates'
  inputs:
    SourceFolder: deployment
    Contents: '*.json'
    TargetFolder: ' $(build.artifactstagingdirectory)/Templates'

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install --production'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/ContosoAir-$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment:'
  inputs:
    azureResourceManagerConnection: 'Mindtree_Chat (e9735a76-e0fb-4c01-b485-f95afa5949d0)'
    subscriptionId: 'e9735a76-e0fb-4c01-b485-f95afa5949d0'
    resourceGroupName: shahrg
    location: 'East US'
    csmFile: '$(System.DefaultWorkingDirectory)/_Shah1986.ContosoAir (1)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/_Shah1986.ContosoAir (1)/drop/Templates/azuredeploy.parameters.json'

- task: ARM Outputs@6
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Mindtree_Chat (e9735a76-e0fb-4c01-b485-f95afa5949d0)'
    resourceGroupName: 'shahrg'
    whenLastDeploymentIsFailed: 'fail'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: githubci2-web-dev'
  inputs:
    azureSubscription: 'Mindtree_Chat (e9735a76-e0fb-4c01-b485-f95afa5949d0)'
    WebAppName: 'githubci2-web-dev'